2025-04-14 21:47:29.856 | WARNING  | __main__:main:18 - Processing your request...
2025-04-14 21:47:29.857 | INFO     | app.agent.base:run:140 - Executing step 1/20
2025-04-14 21:47:29.975 | ERROR    | app.llm:ask_tool:770 - OpenAI API error: Error code: 400 - {'error': {'message': 'deepseek-reasoner does not support Function Calling', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_request_error'}}
2025-04-14 21:47:29.976 | ERROR    | app.llm:ask_tool:776 - API error: Error code: 400 - {'error': {'message': 'deepseek-reasoner does not support Function Calling', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_request_error'}}
2025-04-14 21:47:31.024 | ERROR    | app.llm:ask_tool:770 - OpenAI API error: Error code: 400 - {'error': {'message': 'deepseek-reasoner does not support Function Calling', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_request_error'}}
2025-04-14 21:47:31.025 | ERROR    | app.llm:ask_tool:776 - API error: Error code: 400 - {'error': {'message': 'deepseek-reasoner does not support Function Calling', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_request_error'}}
2025-04-14 21:47:32.599 | ERROR    | app.llm:ask_tool:770 - OpenAI API error: Error code: 400 - {'error': {'message': 'deepseek-reasoner does not support Function Calling', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_request_error'}}
2025-04-14 21:47:32.599 | ERROR    | app.llm:ask_tool:776 - API error: Error code: 400 - {'error': {'message': 'deepseek-reasoner does not support Function Calling', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_request_error'}}
2025-04-14 21:47:34.704 | ERROR    | app.llm:ask_tool:770 - OpenAI API error: Error code: 400 - {'error': {'message': 'deepseek-reasoner does not support Function Calling', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_request_error'}}
2025-04-14 21:47:34.704 | ERROR    | app.llm:ask_tool:776 - API error: Error code: 400 - {'error': {'message': 'deepseek-reasoner does not support Function Calling', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_request_error'}}
